exercise3/mylist/urls.py
from django.conf.urls import url
from list import views

urlpatterns = [
    url(r'^$', views.home_page, name='home'),
]

exercise3/list/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    text = models.TextField(default="")

exercise3/list/views.py
from django.shortcuts import redirect, render
from list.models import Item

# Create your views here.
def home_page(request):
    if request.method == 'POST':
        Item.objects.create(text=request.POST['item_text'])
        return redirect('/')

    items = Item.objects.all()
    if (items.count() == 0):
        theComment = "Yey, waktunya rebahan"
    elif (items.count() < 5):
        theComment = "Sibuk tapi santai"
    else:
        theComment = "Oh tidak"

    return render(request, 'home.html', {'items': items, 'theComment': theComment})

exercise3/list/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Exercise</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

    <center>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="card card-body">
                    <h4>Nesya Dwinanda Sri Fadila</h4>
                    <hr>
                    <p>I studied at the purwokerto telkom technology institute of software engineering study program 2017</p>
                    <p>NIM : 17104030</p>
                </div>
        <table id="id_todo_table" border="1" align ="center">

        </table>
            </div>

        </div>

    </div>

 
        
        
        <hr align="center" width="100%" color="#3a3634" size="2">  

        <h3 align="center" style="margin-top: 30px;">My To Do List</h1>
        <table id="id_list_table" align="center">
            {% for item in items %}
            <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
            {% endfor %}
        </table>

        <form method="POST" align="center" >
            <input name="item_text" id="id_new_item" placeholder="Enter a to-do item" />
            {% csrf_token %}
        </form>

        <div class="card card-body" style="margin-top: 5px;" >
            <h4 id="comment">{{theComment}}</h4>
        </div>
            
    </center>
    </body>
</html>

exercise3/list/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}/lists/{{ list.id }}/add_item{% endblock %}

{% block table %}
  <h3>Comment : </h3>
    {{ list.item_set.all|length }}
    {% if list.item_set.all|length == 0 %}
        <span>yey, waktunya libur</span>
    {% elif list.item_set.all|length > 0 and list.item_set.all|length < 5%}
        <span>sibuk tapi santai</span>
    {% else %}
        <span>oh tidak</span>
    {% endif %}
  <table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
      <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
    {% endfor %}
  </table>
{% endblock %}